name = "SoleModelChecking"
uuid = "f545febf-9d2a-4ce1-b6cd-bbab897c9eb4"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
